CREATE DATABASE SQL_ASSIGN2;
USE SQL_ASSIGN2;


CREATE TABLE EMP_SAL
(S_NO INT, NAME VARCHAR(10), EID CHAR(5), DESI VARCHAR(6), DEPT VARCHAR(10), DOJ VARCHAR(10), SALARY INT, SET_SALARY INT);


SELECT * FROM EMP_SAL;

INSERT INTO EMP_SAL(S_NO, NAME, EID, DESI, DEPT, DOJ, SALARY, SET_SALARY)
VALUES(1, 'SURAJ', 'E0001', 'SDE', 'IT', '21/03/2017', 180000, 198000); 


INSERT INTO EMP_SAL(S_NO, NAME, EID, DESI, DEPT, DOJ, SALARY)
VALUES(2, 'SUDEEPTA', 'E0002', 'SDE', 'IT', '02/05/2019', 80000); 

UPDATE EMP_SAL SET EID = 'E0002'
WHERE S_NO = 2;

INSERT INTO EMP_SAL(S_NO, NAME, EID, DESI, DEPT, DOJ, SALARY)
VALUES(1, 'VENKAT', 'E0003', 'SEO', 'MARKETING', '14/07/2021', 25000); 


INSERT INTO EMP_SAL(S_NO, NAME, EID, DESI, DEPT, DOJ, SALARY)
VALUES(4, 'SUMAN', 'E0004', 'DA', 'DS', '1/05/2023', 90000); 


INSERT INTO EMP_SAL(S_NO, NAME, EID, DESI, DEPT, DOJ, SALARY)
VALUES(5, 'SHUBHAM', 'E0005', 'HR', 'TA', '5/05/2018', 110000); 


INSERT INTO EMP_SAL(S_NO, NAME, EID, DESI, DEPT, DOJ, SALARY)
VALUES(6, 'KIRAN', 'E0006', 'DSCI.', 'DS', '7/07/2017', 180000); 


INSERT INTO EMP_SAL(S_NO, NAME, EID, DESI, DEPT, DOJ, SALARY)
VALUES(7, 'AKANSHA', 'E0007', 'TAB_DEV.', 'DS', '28/10/2022', 50000); 

UPDATE EMP_SAL SET S_NO = 3
WHERE NAME = 'VENKAT';

UPDATE EMP_SAL SET NAME = 'SAM NIKE'
WHERE EID = 'E0004'; 

UPDATE EMP_SAL SET SET_SALARY = SALARY + SALARY * 0.1
WHERE S_NO = 2;

UPDATE EMP_SAL SET SET_SALARY = SALARY + SALARY * 0.1
WHERE S_NO = 3;

UPDATE EMP_SAL SET SET_SALARY = SALARY + SALARY * 0.1
WHERE S_NO = 4;

UPDATE EMP_SAL SET SET_SALARY = SALARY + SALARY * 0.1
WHERE S_NO = 5;

UPDATE EMP_SAL SET SET_SALARY = SALARY + SALARY * 0.1
WHERE S_NO = 6;



SELECT * FROM EMP_SAL;


SELECT *FROM EMP_SAL
WHERE NAME LIKE '%NIKE';

